// LabPilot Mock Data
// Design: Clinical Research Portal — Space Grotesk + Inter + JetBrains Mono
// Deep navy sidebar, off-white content, electric blue accent

export const mockConversations = [
  {
    id: "conv-001",
    title: "Suzuki Optimization — Campaign 4",
    updatedAt: "2025-03-15T10:32:00Z",
    lastMessage: "Top-5 recommendations generated. Best predicted yield: 94.2%",
    messageCount: 8,
  },
  {
    id: "conv-002",
    title: "Ligand Screening — Pd Catalyst",
    updatedAt: "2025-03-14T16:45:00Z",
    lastMessage: "Recommend switching to SPhos ligand for improved selectivity.",
    messageCount: 5,
  },
  {
    id: "conv-003",
    title: "Solvent Optimization Run",
    updatedAt: "2025-03-13T09:20:00Z",
    lastMessage: "THF/water 4:1 shows best yield across 3 reactant pairs.",
    messageCount: 3,
  },
  {
    id: "conv-004",
    title: "Temperature Sweep Analysis",
    updatedAt: "2025-03-12T14:10:00Z",
    lastMessage: "80°C optimal for current catalyst loading.",
    messageCount: 6,
  },
];

export const mockMessages: Record<string, any[]> = {
  "conv-001": [
    {
      id: "msg-001",
      role: "user",
      content: "Recommend top-5 next experiments for current Suzuki-Miyaura campaign.",
      timestamp: "2025-03-15T10:28:00Z",
    },
    {
      id: "msg-002",
      role: "assistant",
      content:
        "Based on the surrogate model and current campaign data, here are the top-5 recommended experiments:",
      timestamp: "2025-03-15T10:29:30Z",
      metadata: {
        recommendation: {
          top_k: 5,
          candidates: [
            {
              rank: 1,
              reactant_1: "PhB(OH)₂",
              catalyst: "Pd(OAc)₂",
              ligand: "SPhos",
              solvent: "THF/H₂O",
              predicted_yield: 94.2,
              uncertainty: 2.1,
              why_now: "High predicted yield with low uncertainty. SPhos ligand underexplored in current campaign.",
              backup: "Use XPhos ligand as alternative — predicted yield 91.8%",
            },
            {
              rank: 2,
              reactant_1: "4-MeOPhB(OH)₂",
              catalyst: "Pd₂(dba)₃",
              ligand: "XPhos",
              solvent: "DMF",
              predicted_yield: 91.5,
              uncertainty: 3.4,
              why_now: "Electron-rich arylboronic acid with bulky ligand shows strong synergy.",
              backup: "Try DavePhos as ligand alternative.",
            },
            {
              rank: 3,
              reactant_1: "PhB(OH)₂",
              catalyst: "Pd(PPh₃)₄",
              ligand: "None",
              solvent: "EtOH/H₂O",
              predicted_yield: 88.9,
              uncertainty: 4.2,
              why_now: "Ligand-free conditions reduce cost. Protic solvent stabilizes Pd(0).",
              backup: "Add 5 mol% PPh₃ if yield drops below 80%.",
            },
            {
              rank: 4,
              reactant_1: "3-ClPhB(OH)₂",
              catalyst: "Pd(OAc)₂",
              ligand: "dppf",
              solvent: "Toluene",
              predicted_yield: 86.3,
              uncertainty: 5.1,
              why_now: "Electron-poor substrate benefits from electron-rich dppf ligand.",
              backup: "Switch to DMSO as co-solvent.",
            },
            {
              rank: 5,
              reactant_1: "PhB(OH)₂",
              catalyst: "Pd(OAc)₂",
              ligand: "PCy₃",
              solvent: "Dioxane",
              predicted_yield: 84.7,
              uncertainty: 6.3,
              why_now: "Bulky phosphine ligand for hindered substrates. Dioxane improves solubility.",
              backup: "Reduce catalyst loading to 1 mol%.",
            },
          ],
        },
        reasoning:
          "The surrogate model (Random Forest, R²=0.91) was queried with 1,247 unexplored conditions. Uncertainty was estimated via bootstrap ensemble. SPhos and XPhos ligands are currently underrepresented in the campaign, making them high-value exploration targets. The Tavily search confirmed recent literature supports SPhos for electron-neutral substrates.",
        agentTrace: [
          { step: 1, tool: "load_surrogate_model", status: "success", duration_ms: 120 },
          { step: 2, tool: "generate_candidate_space", status: "success", duration_ms: 340, candidates: 1247 },
          { step: 3, tool: "predict_yields", status: "success", duration_ms: 890 },
          { step: 4, tool: "rank_by_uncertainty", status: "success", duration_ms: 45 },
          { step: 5, tool: "tavily_search", status: "success", duration_ms: 1200, query: "SPhos ligand Suzuki coupling yield" },
          { step: 6, tool: "generate_reasoning", status: "success", duration_ms: 2100 },
        ],
      },
    },
    {
      id: "msg-003",
      role: "user",
      content: "What is the confidence level for rank 1? Can we reduce uncertainty?",
      timestamp: "2025-03-15T10:31:00Z",
    },
    {
      id: "msg-004",
      role: "assistant",
      content:
        "The rank-1 candidate (PhB(OH)₂ / SPhos / THF:H₂O) has a predicted yield of 94.2% ± 2.1%. This is among the lowest uncertainty values in the candidate set, driven by strong representation of similar conditions in the training data. To further reduce uncertainty, I recommend running 2–3 experiments in this chemical neighborhood to expand the training set before the next recommendation cycle.",
      timestamp: "2025-03-15T10:32:00Z",
      metadata: null,
    },
  ],
};

export const mockTrainingRuns = [
  {
    id: "train-001",
    outputName: "surrogate_suzuki_v3",
    datasetPath: "data/Suzuki-Miyaura/aap9112_Data_File_S1.xlsx",
    targetColumn: "Product_Yield_PCT_Area_UV",
    status: "completed",
    mae: 3.42,
    r2: 0.912,
    trainSize: 892,
    testSize: 224,
    createdAt: "2025-03-15T08:00:00Z",
    artifactPath: "artifacts/surrogate_suzuki_v3.joblib",
  },
  {
    id: "train-002",
    outputName: "surrogate_suzuki_v2",
    datasetPath: "data/Suzuki-Miyaura/aap9112_Data_File_S1.xlsx",
    targetColumn: "Product_Yield_PCT_Area_UV",
    status: "completed",
    mae: 4.81,
    r2: 0.874,
    trainSize: 712,
    testSize: 178,
    createdAt: "2025-03-13T14:30:00Z",
    artifactPath: "artifacts/surrogate_suzuki_v2.joblib",
  },
  {
    id: "train-003",
    outputName: "surrogate_suzuki_v1",
    datasetPath: "data/Suzuki-Miyaura/aap9112_Data_File_S1.xlsx",
    targetColumn: "Product_Yield_PCT_Area_UV",
    status: "completed",
    mae: 6.23,
    r2: 0.821,
    trainSize: 500,
    testSize: 125,
    createdAt: "2025-03-10T11:00:00Z",
    artifactPath: "artifacts/surrogate_suzuki_v1.joblib",
  },
  {
    id: "train-004",
    outputName: "surrogate_buchwald_v1",
    datasetPath: "data/Buchwald/dataset_v1.xlsx",
    targetColumn: "Yield_PCT",
    status: "running",
    mae: null,
    r2: null,
    trainSize: null,
    testSize: null,
    createdAt: "2025-03-15T10:45:00Z",
    artifactPath: null,
  },
];

export const mockExperimentRuns = [
  {
    id: "exp-001",
    strategy: "contextual_linucb",
    datasetPath: "data/Suzuki-Miyaura/aap9112_Data_File_S1.xlsx",
    modelPath: "artifacts/surrogate_suzuki_v3.joblib",
    budget: 20,
    nInit: 3,
    seed: 42,
    rewardMode: "improvement",
    bestYield: 94.2,
    stepsCompleted: 20,
    trajectoryAuc: 87.4,
    thresholdHitRate: 0.85,
    stepToThreshold: 7,
    status: "completed",
    createdAt: "2025-03-15T09:00:00Z",
    steps: [
      { step: 1, observedYield: 62.1, bestSoFar: 62.1 },
      { step: 2, observedYield: 58.4, bestSoFar: 62.1 },
      { step: 3, observedYield: 71.3, bestSoFar: 71.3 },
      { step: 4, observedYield: 74.8, bestSoFar: 74.8 },
      { step: 5, observedYield: 69.2, bestSoFar: 74.8 },
      { step: 6, observedYield: 80.1, bestSoFar: 80.1 },
      { step: 7, observedYield: 83.5, bestSoFar: 83.5 },
      { step: 8, observedYield: 79.0, bestSoFar: 83.5 },
      { step: 9, observedYield: 86.2, bestSoFar: 86.2 },
      { step: 10, observedYield: 84.7, bestSoFar: 86.2 },
      { step: 11, observedYield: 88.9, bestSoFar: 88.9 },
      { step: 12, observedYield: 85.3, bestSoFar: 88.9 },
      { step: 13, observedYield: 90.1, bestSoFar: 90.1 },
      { step: 14, observedYield: 87.6, bestSoFar: 90.1 },
      { step: 15, observedYield: 91.4, bestSoFar: 91.4 },
      { step: 16, observedYield: 89.8, bestSoFar: 91.4 },
      { step: 17, observedYield: 92.7, bestSoFar: 92.7 },
      { step: 18, observedYield: 91.1, bestSoFar: 92.7 },
      { step: 19, observedYield: 93.8, bestSoFar: 93.8 },
      { step: 20, observedYield: 94.2, bestSoFar: 94.2 },
    ],
  },
  {
    id: "exp-002",
    strategy: "greedy",
    datasetPath: "data/Suzuki-Miyaura/aap9112_Data_File_S1.xlsx",
    modelPath: "artifacts/surrogate_suzuki_v3.joblib",
    budget: 20,
    nInit: 3,
    seed: 42,
    rewardMode: "improvement",
    bestYield: 88.1,
    stepsCompleted: 20,
    trajectoryAuc: 79.2,
    thresholdHitRate: 0.60,
    stepToThreshold: 12,
    status: "completed",
    createdAt: "2025-03-14T15:00:00Z",
    steps: [
      { step: 1, observedYield: 60.0, bestSoFar: 60.0 },
      { step: 2, observedYield: 65.3, bestSoFar: 65.3 },
      { step: 3, observedYield: 70.1, bestSoFar: 70.1 },
      { step: 4, observedYield: 68.4, bestSoFar: 70.1 },
      { step: 5, observedYield: 72.8, bestSoFar: 72.8 },
      { step: 6, observedYield: 71.2, bestSoFar: 72.8 },
      { step: 7, observedYield: 74.5, bestSoFar: 74.5 },
      { step: 8, observedYield: 73.0, bestSoFar: 74.5 },
      { step: 9, observedYield: 76.3, bestSoFar: 76.3 },
      { step: 10, observedYield: 75.1, bestSoFar: 76.3 },
      { step: 11, observedYield: 79.8, bestSoFar: 79.8 },
      { step: 12, observedYield: 82.4, bestSoFar: 82.4 },
      { step: 13, observedYield: 81.0, bestSoFar: 82.4 },
      { step: 14, observedYield: 83.7, bestSoFar: 83.7 },
      { step: 15, observedYield: 84.2, bestSoFar: 84.2 },
      { step: 16, observedYield: 83.5, bestSoFar: 84.2 },
      { step: 17, observedYield: 85.9, bestSoFar: 85.9 },
      { step: 18, observedYield: 86.4, bestSoFar: 86.4 },
      { step: 19, observedYield: 87.1, bestSoFar: 87.1 },
      { step: 20, observedYield: 88.1, bestSoFar: 88.1 },
    ],
  },
  {
    id: "exp-003",
    strategy: "random",
    datasetPath: "data/Suzuki-Miyaura/aap9112_Data_File_S1.xlsx",
    modelPath: "artifacts/surrogate_suzuki_v3.joblib",
    budget: 20,
    nInit: 3,
    seed: 42,
    rewardMode: "improvement",
    bestYield: 79.3,
    stepsCompleted: 20,
    trajectoryAuc: 65.1,
    thresholdHitRate: 0.35,
    stepToThreshold: 18,
    status: "completed",
    createdAt: "2025-03-13T11:00:00Z",
    steps: [
      { step: 1, observedYield: 55.2, bestSoFar: 55.2 },
      { step: 2, observedYield: 48.7, bestSoFar: 55.2 },
      { step: 3, observedYield: 62.4, bestSoFar: 62.4 },
      { step: 4, observedYield: 59.1, bestSoFar: 62.4 },
      { step: 5, observedYield: 65.8, bestSoFar: 65.8 },
      { step: 6, observedYield: 52.3, bestSoFar: 65.8 },
      { step: 7, observedYield: 68.1, bestSoFar: 68.1 },
      { step: 8, observedYield: 61.4, bestSoFar: 68.1 },
      { step: 9, observedYield: 70.2, bestSoFar: 70.2 },
      { step: 10, observedYield: 64.5, bestSoFar: 70.2 },
      { step: 11, observedYield: 72.8, bestSoFar: 72.8 },
      { step: 12, observedYield: 58.9, bestSoFar: 72.8 },
      { step: 13, observedYield: 74.1, bestSoFar: 74.1 },
      { step: 14, observedYield: 71.3, bestSoFar: 74.1 },
      { step: 15, observedYield: 75.6, bestSoFar: 75.6 },
      { step: 16, observedYield: 69.8, bestSoFar: 75.6 },
      { step: 17, observedYield: 77.2, bestSoFar: 77.2 },
      { step: 18, observedYield: 79.3, bestSoFar: 79.3 },
      { step: 19, observedYield: 76.1, bestSoFar: 79.3 },
      { step: 20, observedYield: 74.8, bestSoFar: 79.3 },
    ],
  },
  {
    id: "exp-004",
    strategy: "adaptive",
    datasetPath: "data/Suzuki-Miyaura/aap9112_Data_File_S1.xlsx",
    modelPath: "artifacts/surrogate_suzuki_v3.joblib",
    budget: 20,
    nInit: 3,
    seed: 42,
    rewardMode: "improvement",
    bestYield: 91.7,
    stepsCompleted: 20,
    trajectoryAuc: 83.6,
    thresholdHitRate: 0.75,
    stepToThreshold: 9,
    status: "completed",
    createdAt: "2025-03-12T09:00:00Z",
    steps: [
      { step: 1, observedYield: 61.5, bestSoFar: 61.5 },
      { step: 2, observedYield: 67.2, bestSoFar: 67.2 },
      { step: 3, observedYield: 73.4, bestSoFar: 73.4 },
      { step: 4, observedYield: 76.8, bestSoFar: 76.8 },
      { step: 5, observedYield: 74.1, bestSoFar: 76.8 },
      { step: 6, observedYield: 80.5, bestSoFar: 80.5 },
      { step: 7, observedYield: 82.9, bestSoFar: 82.9 },
      { step: 8, observedYield: 81.3, bestSoFar: 82.9 },
      { step: 9, observedYield: 85.7, bestSoFar: 85.7 },
      { step: 10, observedYield: 84.2, bestSoFar: 85.7 },
      { step: 11, observedYield: 87.4, bestSoFar: 87.4 },
      { step: 12, observedYield: 86.1, bestSoFar: 87.4 },
      { step: 13, observedYield: 89.3, bestSoFar: 89.3 },
      { step: 14, observedYield: 88.0, bestSoFar: 89.3 },
      { step: 15, observedYield: 90.2, bestSoFar: 90.2 },
      { step: 16, observedYield: 89.5, bestSoFar: 90.2 },
      { step: 17, observedYield: 91.0, bestSoFar: 91.0 },
      { step: 18, observedYield: 90.4, bestSoFar: 91.0 },
      { step: 19, observedYield: 91.7, bestSoFar: 91.7 },
      { step: 20, observedYield: 90.8, bestSoFar: 91.7 },
    ],
  },
];

export const mockArtifacts = [
  { id: "art-001", name: "surrogate_suzuki_v3.joblib", type: "model", size: "2.4 MB", path: "artifacts/surrogate_suzuki_v3.joblib", createdAt: "2025-03-15T08:05:00Z" },
  { id: "art-002", name: "recommendations_conv001.json", type: "json", size: "12 KB", path: "artifacts/recommendations/conv001.json", createdAt: "2025-03-15T10:29:00Z" },
  { id: "art-003", name: "reasoning_conv001.json", type: "json", size: "8 KB", path: "artifacts/reasoning/conv001.json", createdAt: "2025-03-15T10:29:00Z" },
  { id: "art-004", name: "exp001_best_yield.png", type: "plot", size: "145 KB", path: "artifacts/plots/exp001_best_yield.png", createdAt: "2025-03-15T09:05:00Z" },
  { id: "art-005", name: "exp001_trajectory_auc.png", type: "plot", size: "132 KB", path: "artifacts/plots/exp001_trajectory_auc.png", createdAt: "2025-03-15T09:05:00Z" },
  { id: "art-006", name: "exp001_threshold_hit_rate.png", type: "plot", size: "98 KB", path: "artifacts/plots/exp001_threshold_hit_rate.png", createdAt: "2025-03-15T09:05:00Z" },
  { id: "art-007", name: "benchmark_summary.json", type: "json", size: "24 KB", path: "artifacts/benchmark_summary.json", createdAt: "2025-03-15T09:10:00Z" },
  { id: "art-008", name: "surrogate_suzuki_v2.joblib", type: "model", size: "2.1 MB", path: "artifacts/surrogate_suzuki_v2.joblib", createdAt: "2025-03-13T14:35:00Z" },
];

export const mockBenchmarkSummary = {
  strategies: [
    { name: "contextual_linucb", bestYield: 94.2, trajectoryAuc: 87.4, thresholdHitRate: 0.85, stepToThreshold: 7 },
    { name: "adaptive", bestYield: 91.7, trajectoryAuc: 83.6, thresholdHitRate: 0.75, stepToThreshold: 9 },
    { name: "greedy", bestYield: 88.1, trajectoryAuc: 79.2, thresholdHitRate: 0.60, stepToThreshold: 12 },
    { name: "random", bestYield: 79.3, trajectoryAuc: 65.1, thresholdHitRate: 0.35, stepToThreshold: 18 },
  ],
};
